version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '3000:3000'
    command: ['npm', 'run', 'start:prod']

volumes:
  postgres_data:
